#!/bin/bash
#	自動ワールドバックアップ
# mcsctlと同じディレクトリで実行
export PATH=$PATH:$(dirname $0)
set -e

# skip if no one is logged in from the previous restart
if mcsctl nologin; then
	exit 0
fi

# stop server until exiting
if mcsctl active; then
	mcsctl say "(starting daily backup)"
	mcsctl say "The system is going down in 10 minutes and will restart when finished."
	sleep 10m

	mcsctl say "The system is going down now!"
	sleep 3s

	mcsctl stop
	# wait for stop
	sleep 10s

	# start at exit
	trap 'mcsctl start' EXIT
fi

# take backup all worlds
mcsctl backup all

# remove files older than one month
mcsctl remove +30

# update spigot if necessary
mcsctl autoupdate
