version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      JVM_DD_OPTS: user.timezone="Asia/Tokyo"
      EULA: "TRUE"
      TYPE: "SPIGOT"
      MAX_MEMORY: "2G"
    tty: true
    stdin_open: true
    restart: unless-stopped

  crond:
    build: ./crond
    env_file:
      - ./rcon.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/mnt/src:ro
      - /media/minecraft:/mnt/backup:rw
    restart: unless-stopped
